export const PLATFORM_MODULES = [
  {
    key: "buyer-intelligence",
    title: "Buyer Intelligence",
    icon: "bank",
    summary: "Understand who actually buys.",
    body: "Structured intelligence on Saudi importers, distributors, processors and food-service buyers — what they source, how they buy and what evidence they require. Private commercial information is never exposed.",
    capabilities: ["Buyer profiles and buying patterns", "Requirement qualification", "Evidence status on every record"],
  },
  {
    key: "supplier-intelligence",
    title: "Supplier Intelligence",
    icon: "factory",
    summary: "Understand who can actually supply.",
    body: "Origin-level mapping of African exporters, processors and aggregation networks with capability, capacity, documentation and export-history fields — not unverified directory listings.",
    capabilities: ["Origin and capability mapping", "Capacity and documentation fields", "Verification-aware directory"],
  },
  {
    key: "verification",
    title: "Verification",
    icon: "shield",
    summary: "Validate counterparties.",
    body: "A structured verification stack across identity, registration, commercial capability, requirements, documents, inspection and history, with explicit verified / pending / review / not-verified states.",
    capabilities: ["Counterparty verification workflows", "State-based trust, not logos", "Evidence held against each check"],
  },
  {
    key: "commodity-intelligence",
    title: "Commodity Intelligence",
    icon: "grain",
    summary: "Match specifications and market requirements.",
    body: "Commodity dossiers covering origin, seasonality, grades, documentation, inspection considerations, logistics and risk — with evidence status and last-verified dates.",
    capabilities: ["Grade and specification libraries", "Seasonality and logistics context", "Pricing via quotation, never fabricated"],
  },
  {
    key: "compliance",
    title: "Compliance",
    icon: "stamp",
    summary: "Build documentation before cargo moves.",
    body: "Document workflows and checklists for export, origin, customs and Saudi food-import requirements, coordinated against the transaction timeline rather than assembled under pressure.",
    capabilities: ["Document checklists with owners", "Regulatory guidance from official sources", "Compliance state per transaction"],
  },
  {
    key: "inspection",
    title: "Inspection",
    icon: "flask",
    summary: "Independent evidence.",
    body: "Coordination of sampling, laboratory testing, quality inspection and loading verification through qualified third-party inspection partners, with evidence returned to the transaction record.",
    capabilities: ["Sampling and testing coordination", "Loading supervision evidence", "Partner-performed, MASAR-coordinated"],
  },
  {
    key: "transaction-management",
    title: "Transaction Management",
    icon: "route",
    summary: "Coordinate execution.",
    body: "The operating workspace that moves a matched opportunity through agreement, compliance, inspection, shipment, delivery and settlement with milestones, owners and documents in one place.",
    capabilities: ["Stage-by-stage coordination", "Milestones and responsibilities", "Document and evidence timeline"],
  },
  {
    key: "evidence-layer",
    title: "Evidence Layer",
    icon: "docs",
    summary: "Create a transaction record.",
    body: "Every stage produces evidence: documents, photographs, reports, certificates and communications, assembled into a defensible dossier the parties — and eventually financiers — can rely on.",
    capabilities: ["Chronological evidence dossier", "Traceability from origin to acceptance", "Repeat-trade intelligence"],
  },
  {
    key: "controlled-release",
    title: "Controlled Release",
    icon: "lock",
    summary: "Define what must be satisfied before each step.",
    body: "Release logic gates key transaction actions on satisfied, recorded conditions. Nothing advances on assumption — evidence precedes release, and each decision is attributable.",
    capabilities: ["Condition-based gates", "Attributable release decisions", "Compliance-first sequencing"],
  },
];
