export const WORKFLOW_STAGES = [
  {
    n: 1,
    title: "Demand",
    icon: "target",
    body: "Every MASAR transaction begins with genuine demand: a named Saudi buyer, a real requirement and a commercial purpose. MASAR qualifies the requirement before sourcing begins.",
    outputs: ["Buyer requirement record", "Commodity, grade and quantity profile", "Commercial context and timeline"],
  },
  {
    n: 2,
    title: "Verification",
    icon: "shield",
    body: "The buyer and the requirement are verified — identity, business registration where available, commercial credibility and the realism of the specification.",
    outputs: ["Buyer verification state", "Requirement validation", "Risk and evidence notes"],
  },
  {
    n: 3,
    title: "Supply",
    icon: "factory",
    body: "MASAR identifies suitable African suppliers from origin intelligence — aggregation networks, processors and exporters positioned to meet the requirement.",
    outputs: ["Shortlisted suppliers", "Origin mapping", "Capability comparison"],
  },
  {
    n: 4,
    title: "Qualification",
    icon: "checkCircle",
    body: "Suppliers are qualified against evidence: registration, operating capability, prior exports, documentation readiness and ability to meet the grade and packing requirements.",
    outputs: ["Supplier qualification state", "Capability evidence file", "Gap notes where evidence is missing"],
  },
  {
    n: 5,
    title: "Specification",
    icon: "clipboard",
    body: "Commodity grade, quality parameters, packaging, marking, quantity, Incoterms and commercial requirements are aligned between both parties before commitment.",
    outputs: ["Agreed specification", "Commercial terms summary", "Inspection and evidence plan"],
  },
  {
    n: 6,
    title: "Evidence",
    icon: "flask",
    body: "Independent inspection, sampling, laboratory testing where required, documentation assembly and compliance checks happen before cargo moves.",
    outputs: ["Inspection reports", "Laboratory results where specified", "Export and compliance documentation"],
  },
  {
    n: 7,
    title: "Execution",
    icon: "ship",
    body: "MASAR coordinates the transaction through booking, stuffing, shipment, document exchange and milestone tracking — using qualified logistics partners, not own assets.",
    outputs: ["Shipment coordination", "Document package", "Milestone visibility"],
  },
  {
    n: 8,
    title: "Completion",
    icon: "fileCheck",
    body: "Delivery, acceptance, settlement and the transaction record close the loop — creating the evidence base for repeat trade and future financeability.",
    outputs: ["Delivery and acceptance evidence", "Settlement record", "Complete transaction dossier"],
  },
];

export const TRANSACTION_STAGES = [
  {
    title: "Demand",
    icon: "target",
    purpose: "Capture a genuine, named requirement.",
    enterWhen: "Inquiry received from an identifiable party.",
    exitWhen: "Requirement is complete enough to assess.",
    evidence: "Requirement intake record",
  },
  {
    title: "Qualification",
    icon: "shield",
    purpose: "Verify the counterparties and the requirement.",
    enterWhen: "Requirement record exists.",
    exitWhen: "Buyer and supplier verification states are recorded.",
    evidence: "Verification outcomes and supporting documents",
  },
  {
    title: "Match",
    icon: "network",
    purpose: "Align qualified supply with qualified demand.",
    enterWhen: "Both parties reach a defined verification state.",
    exitWhen: "Counterparties and specification are mutually accepted.",
    evidence: "Match record and specification alignment",
  },
  {
    title: "Commercial agreement",
    icon: "doc",
    purpose: "Lock grade, quantity, price basis, terms and responsibilities.",
    enterWhen: "Specification and counterparties accepted.",
    exitWhen: "Commercial terms documented and acknowledged.",
    evidence: "Contract / proforma and terms",
  },
  {
    title: "Compliance",
    icon: "stamp",
    purpose: "Assemble documentation and regulatory requirements.",
    enterWhen: "Commercial agreement is in place.",
    exitWhen: "Required documents, certificates and permits are on track before movement.",
    evidence: "Document checklist with owners and states",
  },
  {
    title: "Inspection",
    icon: "flask",
    purpose: "Collect independent evidence on quantity and quality.",
    enterWhen: "Goods are ready and specification is fixed.",
    exitWhen: "Inspection and, where required, laboratory results are issued.",
    evidence: "Sampling notes, inspection report, lab results",
  },
  {
    title: "Shipment",
    icon: "ship",
    purpose: "Coordinate handover to qualified logistics partners.",
    enterWhen: "Evidence gates for release are satisfied.",
    exitWhen: "Cargo is loaded, documented and in transit.",
    evidence: "Transport documents, loading evidence, document package",
  },
  {
    title: "Delivery",
    icon: "pin",
    purpose: "Confirm arrival and acceptance against specification.",
    enterWhen: "Shipment is in transit with complete documents.",
    exitWhen: "Buyer acceptance state is recorded, with any claims documented.",
    evidence: "Delivery and acceptance evidence",
  },
  {
    title: "Settlement",
    icon: "bank",
    purpose: "Close payment through the parties' agreed banking channels.",
    enterWhen: "Delivery conditions defined in the agreement are met.",
    exitWhen: "Payment is confirmed by the relevant financial parties.",
    evidence: "Settlement confirmation (held by counterparties and banks)",
  },
  {
    title: "Record",
    icon: "database",
    purpose: "Preserve the complete transaction dossier.",
    enterWhen: "Settlement and acceptance are complete.",
    exitWhen: "Dossier is stored, indexed and available to the verified parties.",
    evidence: "Transaction record supporting repeat trade and financing",
  },
];

export const RELEASE_GATES = [
  { t: "Order and counterparty verified", d: "No sourcing or matching advances until identity and requirement checks are recorded." },
  { t: "Specification and grade aligned", d: "Quality parameters, packaging and commercial terms are documented and acknowledged." },
  { t: "Documentation complete", d: "Export, import, origin and product documents are identified with owners and states." },
  { t: "Independent inspection passed", d: "Sampling and testing outcomes match the agreed specification before release." },
  { t: "Compliance confirmed", d: "Applicable regulatory and food-import requirements are evidenced." },
  { t: "Release authorized and recorded", d: "Each release decision, who made it and on what evidence is preserved in the record." },
];

export const VERIFICATION_STACK = [
  { key: "company", title: "Company verification", d: "Legal identity, registration and operating status of the counterparty.", icon: "building" },
  { key: "identity", title: "Identity", d: "Confirmation that the people acting for a company are authorized to do so.", icon: "user" },
  { key: "registration", title: "Business registration", d: "Registration and export/import standing where public records and documents allow.", icon: "stamp" },
  { key: "commercial", title: "Commercial capability", d: "Evidence of genuine commercial activity, trade references and operational history.", icon: "bank" },
  { key: "supplier", title: "Supplier capability", d: "Capacity, processing, packing, warehousing and documented ability to perform.", icon: "factory" },
  { key: "requirement", title: "Buyer requirement validation", d: "The requirement is real, specific and commercially coherent.", icon: "target" },
  { key: "documents", title: "Document verification", d: "Certificates and shipping documents are checked for consistency and authenticity indicators.", icon: "docs" },
  { key: "inspection", title: "Inspection", d: "Independent sampling, testing and loading evidence from qualified third parties.", icon: "flask" },
  { key: "history", title: "Transaction history", d: "Completed, documented transactions build a repeatable trust record over time.", icon: "database" },
];

export const VERIFICATION_STATES = [
  { key: "verified", label: "Verified", tone: "success", d: "Checks completed and supported by evidence on file." },
  { key: "pending", label: "Pending", tone: "warning", d: "Verification initiated; evidence outstanding." },
  { key: "review", label: "Requires review", tone: "warning", d: "Evidence is inconsistent or needs human assessment." },
  { key: "none", label: "Not verified", tone: "muted", d: "No verification has been performed. No claim of verified status is made." },
];
